### ISSUE TITLE
Compile the ipa

### ISSUE THREAD

**Issue by ghost** [arx8x/v0rtexNonce#21]
I have problems to compile the ipa with new offsets (iSE iOS 10.3.1) due to signing certificate, can someone compile the ipa for me, with the right offsets. 
My device is iPhone SE on iOS 10.3.1
Thanks a lot

**Comment by arx8x** [comment]
change the bundle identifier, use your own account from the dropdown box. If you still can't solve it, search youtube with the error

**Comment by arx8x** [comment]
also, I'll be adding a new build in the release section in some hours

**Comment by ghost** [comment]
now works, just create a new Apple ID
