### ISSUE TITLE
iPhone7+ 10.3.1 v0rtex Error

### ISSUE THREAD

**Issue by ScknCbt** [arx8x/v0rtexNonce#25]
i download the newest v0rtexnonce1.1.ipa but i get always 
Error
v0rtex eploit failed 
Please reboot and try Again.

**Comment by arx8x** [comment]
post logs

**Comment by u-C-m** [comment]
was that resolved? if not, is it bc logs are missing? I would like to provide them, the only issue is that I'm using vmware and don't exactly know how to get those logs
