### ISSUE TITLE
Support for iPhone 7 10.2.1

### ISSUE THREAD

**Issue by riththerift** [arx8x/v0rtexNonce#27]
Hi,

Is there any chance that this will support iPhone 7 running iOS 10.2.1.

**Comment by cowpod** [comment]
Eventually, yes. You could help by using find_offsets.sh on the iphone 7 10.2.1 ipsw and posting the offsets here.

**Comment by riththerift** [comment]
I would love to help. Could you tell me step by step on how to do this?

**Comment by arx8x** [comment]
This is not an issue.
