### ISSUE TITLE
iPhone 6 Plus/iOS 10.3.2 offset I have been tested

### ISSUE THREAD

**Issue by sagexy** [arx8x/v0rtexNonce#36]
as the title I have been tested on iPhone 6 Plus iOS 10.3.2 ! the offset is:

            OFFSET_ZONE_MAP                             = 0xfffffff007558478;
            OFFSET_KERNEL_MAP                           = 0xfffffff0075b4050;
            OFFSET_KERNEL_TASK                          = 0xfffffff0075b4048;
            OFFSET_REALHOST                             = 0xfffffff00753aba0;
            OFFSET_BZERO                                = 0xfffffff00708df80;
            OFFSET_BCOPY                                = 0xfffffff00708ddc0;
            OFFSET_COPYIN                               = 0xfffffff00718d37c;
            OFFSET_COPYOUT                              = 0xfffffff00718d570;
            OFFSET_IPC_PORT_ALLOC_SPECIAL               = 0xfffffff0070a60b4;
            OFFSET_IPC_KOBJECT_SET                      = 0xfffffff0070b938c;
            OFFSET_IPC_PORT_MAKE_SEND                   = 0xfffffff0070a5bd8;
            OFFSET_IOSURFACEROOTUSERCLIENT_VTAB         = 0xfffffff006eee1b8;
            OFFSET_ROP_ADD_X0_X0_0x10                   = 0xfffffff0064b2174;

![image](https://user-images.githubusercontent.com/4734448/34350857-0f104a00-ea54-11e7-9d42-5441fcbebac8.png)

and now I'm in iOS 11.1.2 ✌️

**Comment by arx8x** [comment]
Thank you
