### ISSUE TITLE
on v 1.1 and also on 1.3 iphone 6 ios 10.3.1 current generator unavailable and failed to validate generator

### ISSUE THREAD

**Issue by Luken36** [arx8x/v0rtexNonce#40]
hi finally the app open correcly but it don't show the current generator

**Comment by ghost** [comment]
You need to press the empty area and set you nonce there....

**Comment by arx8x** [comment]
@Luken36 A screenshot would be nice

**Comment by Darkaim63** [comment]
I can provide a screenshot. I am in the exact same position as @Luken36 . I have an iPhone 6 on 10.3.1 and I get the same error @arx8x .

**Comment by Darkaim63** [comment]
![unnamed](https://user-images.githubusercontent.com/13300875/34369063-c4c09580-ea6d-11e7-9825-b3a2198bf0d4.jpg)

**Comment by Darkaim63** [comment]
![unnamed](https://user-images.githubusercontent.com/13300875/34369085-ee93780a-ea6d-11e7-97f5-0721b0cbe0ad.jpg)

Edit: When I go to set my 11.1.2 nonce from my saved blob and hit return nothing happens. Just to clarify what actually happens besides the -unavilable-

**Comment by arx8x** [comment]
can you post a screenshot with  your generator pasted on the text field?

**Comment by mikewng19** [comment]
**_I'm getting the same issue on my iPhone 6 but iOS 10.3.3_**
![img_9976](https://user-images.githubusercontent.com/25393705/34371685-483cc300-ea9d-11e7-85dd-e1b1b450f257.PNG)
![img_9975](https://user-images.githubusercontent.com/25393705/34371686-484a905c-ea9d-11e7-9195-2bd5de1eb890.PNG)

**Comment by Darkaim63** [comment]
I get that exact same error @mikewng19

**Comment by arx8x** [comment]
That issue should be fixed in this commit. Clone and re-compile

**Comment by Luken36** [comment]
![img-1162](https://user-images.githubusercontent.com/34871117/34389062-ad4b1220-eb37-11e7-88cd-75ef72cd2aec.PNG)

![img-1161](https://user-images.githubusercontent.com/34871117/34389057-a641e346-eb37-11e7-8c8a-6ef97522c9cf.PNG)
Unfortunaltely last version made same error of old version

**Comment by arx8x** [comment]
@Luken36 Why did you close the issue?

**Comment by Luken36** [comment]
because on reddit i found a solution, now works, i compile it with xcode before i tried ipa

**Comment by Luken36** [comment]
it initialy don't show current generator but it set new generator of blob so it works

**Comment by arx8x** [comment]
Oh okay. I was asking you to compile

**Comment by Luken36** [comment]
ah okay, i don't see when you said that
