### ISSUE TITLE
iPhone6,2 iOS 10.2 tested.

### ISSUE THREAD

**Issue by d0ppl3r** [arx8x/v0rtexNonce#45]
Test 1: Did it from 1st attempt
Test 2: Did it from 3rd attempt
Test 3: Did it from 1st attempt(+entered into jailbroken mode from 1st attempt with yalu102 lol)
https://imgur.com/a/rKw88
If you want,I can test it on 5s with 10.2.1(I have 10.2-10.3.3 SHSH2,but 10.3.1-10.3.3 were found by me and already trsted)

**Comment by d0ppl3r** [comment]
P.S: It's iPhone5s iPhone6,2 model with UpScale :/

**Comment by arx8x** [comment]
So, the offsets for iPhone6,2 work?
Works before and after you jailbreak with yalu?

**Comment by d0ppl3r** [comment]
+.
1 and 3 screenshots are made in jbroken mode,2 screenshot in non-jbroken mode.

**Comment by arx8x** [comment]
Thank you for verifying
